[project]
name = "ComfyUI-NanoGPT_ImageGeneration"
description = "Custom node to generate a image using NanoGPT API"
version = "0.9.1"
license = {file = "LICENSE"}
dependencies  = []

[project.urls]
Repository = "https://github.com/jochst/ComfyUI-NanoGPT_ImageGeneration"

[tool.comfy]
PublisherId = "myonmu0"
DisplayName = "ComfyUI-NanoGPT_ImageGeneration"
Icon = ""
